
test:
  image: docker:latest
  services:
  - docker:dind
  script:
    - 'echo gem: --no-document > $HOME/.gemrc'
    - apk update
    - apk add --update build-base git libffi-dev ruby-dev ruby-bundler python python-dev py-pip 
    - gem install kitchen-docker kitchen-inspec berkshelf
    - bundler install
    - pip install -r requirements.txt
    - kitchen verify
