---
driver:
  name: docker
  hostname: docker-formula.ci.local
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  # No need for chef as we're not using busser
  require_chef: false
  formula: docker
  pillars-from-docker:
    docker.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - docker
  state_top:
    base:
      '*':
        - docker

platforms:
  - name: debian-9

suites:
  - name: docker
    provisioner:
      state_top:
        base:
          '*':
            - docker

verifier:
  name: shell
  remote_exec: false
  # Command changed to allow running the same tests with different parameters
  command: py.test --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$(echo $KITCHEN_SUITE | sed 's/_.*//')
