# vim: ft=jinja sts=2 ts=2 sw=2 et ai

docker:
  package:
    name: docker-ce
    version: "18.03.0~ce-0~debian"
  # Environment variables for the docker process
  environment:
    DOCKER_OPTS: "-H fd://"
